services:
  postgres:
    container_name: ocr-postgres-dev
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${PG_OCR_DB}
      POSTGRES_USER: ${PG_OCR_USER}
      POSTGRES_PASSWORD: ${PG_OCR_PASSWORD}
    ports:
      - "127.0.0.1:5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    container_name: ocr-redis-dev
    image: redis:8-alpine
    command: ["redis-server", "--requirepass", "${REDIS_OCR_PASSWORD}"]
    ports:
      - "127.0.0.1:6379:6379"

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: ocr-rabbitmq-dev
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:15692:15692"

  garage:
    image: dxflrs/garage:v2.3.0
    container_name: ocr-garage-dev
    command: ["/garage", "server", "--single-node"]
    ports:
      - "3900:3900"
    volumes:
      - garage-data:/data
      - ./garage.toml:/etc/garage.toml:ro

volumes:
  pgdata:
  garage-data:
