/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidateEmailRouteImport } from './routes/validate-email'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PasswordForgottenRouteImport } from './routes/password-forgotten'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProcessesRouteImport } from './routes/_auth/processes'
import { Route as DownloadsProcessesIdRouteImport } from './routes/downloads/processes/$id'

const ValidateEmailRoute = ValidateEmailRouteImport.update({
  id: '/validate-email',
  path: '/validate-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgottenRoute = PasswordForgottenRouteImport.update({
  id: '/password-forgotten',
  path: '/password-forgotten',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProcessesRoute = AuthProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DownloadsProcessesIdRoute = DownloadsProcessesIdRouteImport.update({
  id: '/downloads/processes/$id',
  path: '/downloads/processes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/password-forgotten': typeof PasswordForgottenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/validate-email': typeof ValidateEmailRoute
  '/processes': typeof AuthProcessesRoute
  '/downloads/processes/$id': typeof DownloadsProcessesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/password-forgotten': typeof PasswordForgottenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/validate-email': typeof ValidateEmailRoute
  '/processes': typeof AuthProcessesRoute
  '/downloads/processes/$id': typeof DownloadsProcessesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/cgu': typeof CguRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/password-forgotten': typeof PasswordForgottenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/validate-email': typeof ValidateEmailRoute
  '/_auth/processes': typeof AuthProcessesRoute
  '/downloads/processes/$id': typeof DownloadsProcessesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/login'
    | '/metrics'
    | '/password-forgotten'
    | '/reset-password'
    | '/sign-up'
    | '/validate-email'
    | '/processes'
    | '/downloads/processes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/login'
    | '/metrics'
    | '/password-forgotten'
    | '/reset-password'
    | '/sign-up'
    | '/validate-email'
    | '/processes'
    | '/downloads/processes/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/cgu'
    | '/login'
    | '/metrics'
    | '/password-forgotten'
    | '/reset-password'
    | '/sign-up'
    | '/validate-email'
    | '/_auth/processes'
    | '/downloads/processes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CguRoute: typeof CguRoute
  LoginRoute: typeof LoginRoute
  MetricsRoute: typeof MetricsRoute
  PasswordForgottenRoute: typeof PasswordForgottenRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignUpRoute: typeof SignUpRoute
  ValidateEmailRoute: typeof ValidateEmailRoute
  DownloadsProcessesIdRoute: typeof DownloadsProcessesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validate-email': {
      id: '/validate-email'
      path: '/validate-email'
      fullPath: '/validate-email'
      preLoaderRoute: typeof ValidateEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-forgotten': {
      id: '/password-forgotten'
      path: '/password-forgotten'
      fullPath: '/password-forgotten'
      preLoaderRoute: typeof PasswordForgottenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/processes': {
      id: '/_auth/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof AuthProcessesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/downloads/processes/$id': {
      id: '/downloads/processes/$id'
      path: '/downloads/processes/$id'
      fullPath: '/downloads/processes/$id'
      preLoaderRoute: typeof DownloadsProcessesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthProcessesRoute: typeof AuthProcessesRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthProcessesRoute: AuthProcessesRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CguRoute: CguRoute,
  LoginRoute: LoginRoute,
  MetricsRoute: MetricsRoute,
  PasswordForgottenRoute: PasswordForgottenRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignUpRoute: SignUpRoute,
  ValidateEmailRoute: ValidateEmailRoute,
  DownloadsProcessesIdRoute: DownloadsProcessesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
